"""
Marketplace smart contract service.
"""

import json
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Union

from fastapi import HTTPException
from ..schemas.dataset_schema import WalletType
from ..schemas.marketplace_schema import MarketplaceDataItem
from web3 import Web3
from web3.contract import Contract

from ..config.settings import Settings


def uuid_to_bytes32(id: Union[str, uuid.UUID]) -> bytes:
    """Convert listing UUID string to bytes32 format.

    Args:
        id (Union[str, uuid.UUID]): Listing UUID string or UUID instance

    Raises:
        HTTPException: Raised if the id is not a valid UUID

    Returns:
        bytes: Listing ID in bytes32 format
    """

    try:
        u = id if isinstance(id, uuid.UUID) else uuid.UUID(id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid id UUID") from exc
    return u.bytes + b"\x00" * 16


def wallet_id(
    wallet_type: Union[WalletType, str], address: str, settings: Settings
) -> bytes:
    """Generate wallet ID bytes from wallet type and address.

    Args:
        wallet_type (WalletType): Wallet type enum value
        address (str): Wallet address or public key
        settings (Settings): Application settings instance

    Returns:
        bytes: Wallet ID bytes generated by keccak256 hash
    """

    wallet_type_str = (
        wallet_type.value.lower()
        if isinstance(wallet_type, WalletType)
        else str(wallet_type).lower()
    )
    if wallet_type_str == WalletType.EVM:
        chain = f"eip155:{settings.chain_id}"
        addr = Web3.to_checksum_address(address).lower()
        payload = f"{chain}:{addr}"
    elif wallet_type_str == WalletType.SOLANA:
        payload = f"solana:{address}"
    elif wallet_type_str == WalletType.BTC:
        payload = f"bitcoin:{address}"
    else:
        payload = f"{wallet_type_str}:{address}"
    return Web3.keccak(text=payload)


@lru_cache(maxsize=1)
def _load_abi(abi_path: str) -> List[Dict[str, Any]]:
    """Load contract ABI from JSON file.

    Args:
        abi_path (str): Path to ABI JSON file

    Returns:
        List[Dict[str, Any]]: Contract ABI
    """

    return json.loads(Path(abi_path).read_text())


def _get_web3(settings: Settings) -> Web3:
    """Create and return a Web3 instance.

    Args:
        settings (Settings): Application settings instance

    Returns:
        Web3: Web3 instance
    """

    return Web3(Web3.HTTPProvider(settings.rpc_url))


def _get_contract(settings: Settings) -> Contract:
    """Create and return a Contract instance.

    Args:
        settings (Settings): Application settings instance

    Returns:
        Contract: Contract instance
    """

    w3 = _get_web3(settings)
    abi = _load_abi(settings.contract_abi_path)
    return w3.eth.contract(
        address=Web3.to_checksum_address(settings.contract_address), abi=abi
    )


def _to_hex(value: Any) -> str:
    if isinstance(value, (bytes, bytearray)):
        return Web3.to_hex(value)
    return str(value)


def _item_view_to_schema(raw: Any) -> MarketplaceDataItem:
    if isinstance(raw, dict):
        item_id = raw.get("itemId") or raw.get("item_id") or raw.get("id")
        title = raw.get("title")
        description = raw.get("description")
        seller = raw.get("seller")
        price = raw.get("price")
        dataset_url = raw.get("datasetUrl") or raw.get("dataset_url")
        dataset_hash = raw.get("datasetHash") or raw.get("dataset_hash")
        signature_url = raw.get("signatureUrl") or raw.get("signature_url")
        signature_hash = raw.get("signatureHash") or raw.get("signature_hash")
        exists = raw.get("exists")
        purchase_count = (
            raw.get("purchaseCount")
            if "purchaseCount" in raw
            else raw.get("purchase_count")
        )
    else:
        (
            item_id,
            title,
            description,
            seller,
            price,
            dataset_url,
            dataset_hash,
            signature_url,
            signature_hash,
            exists,
            purchase_count,
        ) = raw

    return MarketplaceDataItem(
        id=_to_hex(item_id),
        title=title,
        description=description,
        seller=seller,
        price=price,
        dataset_url=dataset_url,
        dataset_hash=_to_hex(dataset_hash),
        signature_url=signature_url,
        signature_hash=_to_hex(signature_hash),
        exists=bool(exists),
        purchase_count=int(purchase_count),
    )


def _send_tx(function, settings: Settings, value: int = 0) -> str:
    """Send a transaction to the smart contract.

    Args:
        function: Contract function to call
        settings (Settings): Application settings instance
        value (int, optional): Amount of wei to send with the transaction. Defaults to 0.

    Returns:
        str: Transaction hash
    """

    w3 = _get_web3(settings)
    account = w3.eth.account.from_key(settings.server_private_key.get_secret_value())
    tx = function.build_transaction(
        {
            "from": account.address,
            "nonce": w3.eth.get_transaction_count(account.address),
            "chainId": settings.chain_id,
            "value": value,
        }
    )
    try:
        tx["gas"] = w3.eth.estimate_gas(tx)
    except Exception:
        tx["gas"] = 1_000_000
    tx["gasPrice"] = w3.eth.gas_price

    signed = account.sign_transaction(tx)
    tx_hash = w3.eth.send_raw_transaction(signed.rawTransaction)
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    if receipt.status != 1:
        raise HTTPException(status_code=502, detail="Transaction failed")
    return tx_hash.hex()


def max_price(settings: Settings) -> int:
    """Get the maximum price allowed for listings.

    Args:
        settings (Settings): Application settings instance

    Returns:
        int: Maximum price allowed for listings
    """

    return _get_contract(settings).functions.MAX_PRICE().call()


def fee_bps(settings: Settings) -> int:
    """Get the fee basis points configured in the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        int: Fee basis points configured in the contract
    """

    return _get_contract(settings).functions.feeBps().call()


def fee_recipient(settings: Settings) -> str:
    """Get the fee recipient address configured in the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Fee recipient address configured in the contract
    """

    return _get_contract(settings).functions.feeRecipient().call()


def owner(settings: Settings) -> str:
    """Get the owner address of the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Owner address of the contract
    """

    return _get_contract(settings).functions.owner().call()


def get_item_view(listing_id: str, settings: Settings) -> MarketplaceDataItem:
    """Get the item view for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        settings (Settings): Application settings instance

    Returns:
        MarketplaceDataItem: Item view data
    """

    item_id = uuid_to_bytes32(listing_id)
    raw = _get_contract(settings).functions.getItemView(item_id).call()
    return _item_view_to_schema(raw)


def get_items(start: int, count: int, settings: Settings) -> List[MarketplaceDataItem]:
    """Get a list of item views from the contract.

    Args:
        start (int): Starting index
        count (int): Number of items to retrieve
        settings (Settings): Application settings instance

    Returns:
        List[MarketplaceDataItem]: List of item views
    """
    raw_items = _get_contract(settings).functions.getItems(start, count).call()
    return [_item_view_to_schema(item) for item in raw_items]


def get_all_items(settings: Settings) -> List[MarketplaceDataItem]:
    """Get all item views from the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        List[MarketplaceDataItem]: List of all item views
    """

    raw_items = _get_contract(settings).functions.getAllItems().call()
    return [_item_view_to_schema(item) for item in raw_items]


def has_access(id: str, wallet_id_bytes: bytes, settings: Settings) -> bool:
    """Check if a wallet has access to a specific listing.

    Args:
        id (str): Listing UUID string
        wallet_id_bytes (bytes): Wallet ID bytes
        settings (Settings): Application settings instance

    Returns:
        bool: True if the wallet has access, False otherwise
    """

    item_id = uuid_to_bytes32(id)
    return _get_contract(settings).functions.hasAccess(item_id, wallet_id_bytes).call()


def create_item(
    id: str,
    title: str,
    description: str,
    seller: str,
    price: int,
    dataset_url: str,
    dataset_hash: str,
    signature_url: str,
    signature_hash: str,
    settings: Settings,
) -> str:
    """Create a new item listing in the contract.

    Args:
        listing_id (str): Listing UUID string
        title (str): Item title
        description (str): Item description
        seller (str): Seller address
        price (int): Item price
        dataset_url (str): Dataset URL
        dataset_hash (str): Dataset hash
        signature_url (str): Signature URL
        signature_hash (str): Signature hash
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(id)
    tx = contract.functions.createItem(
        item_id,
        title,
        description,
        Web3.to_checksum_address(seller),
        price,
        dataset_url,
        Web3.to_bytes(hexstr=dataset_hash),
        signature_url,
        Web3.to_bytes(hexstr=signature_hash),
    )
    return _send_tx(tx, settings)


def buy_item(listing_id: str, value_wei: int, settings: Settings) -> str:
    """Buy an item from the contract.

    Args:
        listing_id (str): Listing UUID string
        value_wei (int): Value in Wei to send with the transaction
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.buyItem(item_id)
    return _send_tx(tx, settings, value=value_wei)


def update_dataset_url(listing_id: str, new_url: str, settings: Settings) -> str:
    """Update the dataset URL for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_url (str): New dataset URL
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.updateDatasetUrl(item_id, new_url)
    return _send_tx(tx, settings)


def update_signature(
    listing_id: str, new_url: str, new_hash: str, settings: Settings
) -> str:
    """Update the signature URL and hash for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_url (str): New signature URL
        new_hash (str): New signature hash
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.updateSignature(
        item_id, new_url, Web3.to_bytes(hexstr=new_hash)
    )
    return _send_tx(tx, settings)


def update_price(listing_id: str, new_price: int, settings: Settings) -> str:
    """Update the price for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_price (int): New price for the item
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.updatePrice(item_id, new_price)
    return _send_tx(tx, settings)


def set_fee_config(
    fee_recipient_addr: str, fee_bps_value: int, settings: Settings
) -> str:
    """Set the fee recipient address and fee basis points in the contract.

    Args:
        fee_recipient_addr (str): Fee recipient address
        fee_bps_value (int): Fee basis points value
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    tx = contract.functions.setFeeConfig(
        Web3.to_checksum_address(fee_recipient_addr), fee_bps_value
    )
    return _send_tx(tx, settings)


def transfer_ownership(new_owner: str, settings: Settings) -> str:
    """Transfer ownership of the contract to a new owner.

    Args:
        new_owner (str): New owner's address
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    tx = contract.functions.transferOwnership(Web3.to_checksum_address(new_owner))
    return _send_tx(tx, settings)


def renounce_ownership(settings: Settings) -> str:
    """Renounce ownership of the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    tx = contract.functions.renounceOwnership()
    return _send_tx(tx, settings)


def grant_access(listing_id: str, wallet_id_bytes: bytes, settings: Settings) -> str:
    """Grant access to a wallet for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        wallet_id_bytes (bytes): Wallet ID in bytes
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.grantAccess(item_id, wallet_id_bytes)
    return _send_tx(tx, settings)
