"""
Marketplace smart contract service.
"""

import json
import logging
import uuid
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Union

from fastapi import HTTPException
from ..schemas.dataset_schema import WalletType
from ..schemas.marketplace_schema import MarketplaceDataItem
from web3 import Web3
from web3.contract import Contract

from ..config.settings import Settings

logger = logging.getLogger(__name__)


def _raise_bad_request(detail: str, exc: Exception) -> None:
    logger.warning("%s: %s", detail, str(exc))
    raise HTTPException(status_code=400, detail=detail) from exc


def _raise_internal_config(detail: str, exc: Exception) -> None:
    logger.exception("%s", detail)
    raise HTTPException(status_code=500, detail=detail) from exc


def _raise_upstream(detail: str, exc: Exception) -> None:
    logger.exception("%s", detail)
    raise HTTPException(status_code=502, detail=f"{detail}: {str(exc)}") from exc


def uuid_to_bytes32(id: Union[str, uuid.UUID]) -> bytes:
    """Convert listing UUID string to bytes32 format.

    Args:
        id (Union[str, uuid.UUID]): Listing UUID string or UUID instance

    Raises:
        HTTPException: Raised if the id is not a valid UUID

    Returns:
        bytes: Listing ID in bytes32 format
    """

    try:
        u = id if isinstance(id, uuid.UUID) else uuid.UUID(id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid id UUID") from exc
    return u.bytes + b"\x00" * 16


def wallet_id(
    wallet_type: Union[WalletType, str], address: str, settings: Settings
) -> bytes:
    """Generate wallet ID bytes from wallet type and address.

    Args:
        wallet_type (WalletType): Wallet type enum value
        address (str): Wallet address or public key
        settings (Settings): Application settings instance

    Returns:
        bytes: Wallet ID bytes generated by keccak256 hash
    """

    wallet_type_str = (
        wallet_type.value.lower()
        if isinstance(wallet_type, WalletType)
        else str(wallet_type).lower()
    )
    if wallet_type_str == WalletType.EVM.value:
        chain = f"eip155:{settings.chain_id}"
        try:
            checksum_address = Web3.to_checksum_address(address)
        except ValueError as exc:
            _raise_bad_request("Invalid EVM address provided", exc)
        addr = Web3.to_hex(Web3.to_bytes(hexstr=checksum_address))
        payload = f"{chain}:{addr}"
    elif wallet_type_str == WalletType.SOLANA.value:
        payload = f"solana:{address}"
    elif wallet_type_str == WalletType.BTC.value:
        payload = f"bitcoin:{address}"
    else:
        payload = f"{wallet_type_str}:{address}"
    return Web3.keccak(text=payload)


@lru_cache(maxsize=1)
def _load_abi(abi_path: str) -> List[Dict[str, Any]]:
    """Load contract ABI from JSON file.

    Args:
        abi_path (str): Path to ABI JSON file

    Returns:
        List[Dict[str, Any]]: Contract ABI
    """

    try:
        return json.loads(Path(abi_path).read_text())
    except FileNotFoundError as exc:
        _raise_internal_config(
            f"Contract ABI file not found at path: {abi_path}",
            exc,
        )
    except json.JSONDecodeError as exc:
        _raise_internal_config(
            f"Contract ABI file is not valid JSON: {abi_path}",
            exc,
        )


def _get_web3(settings: Settings) -> Web3:
    """Create and return a Web3 instance.

    Args:
        settings (Settings): Application settings instance

    Returns:
        Web3: Web3 instance
    """

    w3 = Web3(Web3.HTTPProvider(settings.rpc_url))
    if not w3.is_connected():
        logger.error("RPC node is unreachable at %s", settings.rpc_url)
        raise HTTPException(
            status_code=502,
            detail=f"RPC node unreachable at {settings.rpc_url}",
        )
    return w3


def _get_contract(settings: Settings) -> Contract:
    """Create and return a Contract instance.

    Args:
        settings (Settings): Application settings instance

    Returns:
        Contract: Contract instance
    """

    w3 = _get_web3(settings)
    abi = _load_abi(settings.contract_abi_path)
    try:
        checksum_address = Web3.to_checksum_address(settings.contract_address)
    except ValueError as exc:
        _raise_internal_config("Invalid CONTRACT_ADDRESS configuration", exc)
    try:
        return w3.eth.contract(address=checksum_address, abi=abi)
    except Exception as exc:
        _raise_internal_config("Failed to initialize contract client", exc)


def _to_hex(value: Any) -> str:
    if isinstance(value, (bytes, bytearray)):
        return Web3.to_hex(value)
    return str(value)


def _item_view_to_schema(raw: Any) -> MarketplaceDataItem:
    if isinstance(raw, dict):
        item_id = raw.get("itemId") or raw.get("item_id") or raw.get("id")
        title = raw.get("title")
        description = raw.get("description")
        seller = raw.get("seller")
        price = raw.get("price")
        dataset_url = raw.get("datasetUrl") or raw.get("dataset_url")
        dataset_hash = raw.get("datasetHash") or raw.get("dataset_hash")
        signature_url = raw.get("signatureUrl") or raw.get("signature_url")
        signature_hash = raw.get("signatureHash") or raw.get("signature_hash")
        exists = raw.get("exists")
        purchase_count = (
            raw.get("purchaseCount")
            if "purchaseCount" in raw
            else raw.get("purchase_count")
        )
    else:
        (
            item_id,
            title,
            description,
            seller,
            price,
            dataset_url,
            dataset_hash,
            signature_url,
            signature_hash,
            exists,
            purchase_count,
        ) = raw

    return MarketplaceDataItem(
        id=_to_hex(item_id),
        title=title,
        description=description,
        seller=seller,
        price=price,
        dataset_url=dataset_url,
        dataset_hash=_to_hex(dataset_hash),
        signature_url=signature_url,
        signature_hash=_to_hex(signature_hash),
        exists=bool(exists),
        purchase_count=int(purchase_count),
    )


def _send_tx(function, settings: Settings, value: int = 0) -> str:
    """Send a transaction to the smart contract.

    Args:
        function: Contract function to call
        settings (Settings): Application settings instance
        value (int, optional): Amount of wei to send with the transaction. Defaults to 0.

    Returns:
        str: Transaction hash
    """

    w3 = _get_web3(settings)
    try:
        rpc_chain_id = w3.eth.chain_id
    except Exception as exc:
        _raise_upstream("Failed to fetch chain id from RPC", exc)
    if rpc_chain_id != settings.chain_id:
        logger.error(
            "Chain ID mismatch. settings.chain_id=%s rpc.chain_id=%s",
            settings.chain_id,
            rpc_chain_id,
        )
        raise HTTPException(
            status_code=500,
            detail=(
                f"Chain ID mismatch: settings={settings.chain_id}, rpc={rpc_chain_id}. "
                "Update CHAIN_ID or RPC_URL."
            ),
        )
    try:
        account = w3.eth.account.from_key(
            settings.server_private_key.get_secret_value()
        )
    except Exception as exc:
        _raise_internal_config("Invalid SERVER_PRIVATE_KEY configuration", exc)
    try:
        tx = function.build_transaction(
            {
                "from": account.address,
                "nonce": w3.eth.get_transaction_count(account.address, "pending"),
                "chainId": settings.chain_id,
                "value": value,
            }
        )
    except Exception as exc:
        _raise_upstream("Failed to build contract transaction", exc)
    try:
        tx["gas"] = w3.eth.estimate_gas(tx)
    except Exception as exc:
        logger.warning(
            "Gas estimation failed; using fallback gas limit 1000000. "
            "from=%s nonce=%s value=%s error=%s",
            account.address,
            tx.get("nonce"),
            value,
            str(exc),
        )
        tx["gas"] = 1_000_000
    try:
        latest_block = w3.eth.get_block("latest")
        base_fee = latest_block.get("baseFeePerGas", 0)
        priority_fee = w3.to_wei(1, "gwei")
        tx["maxPriorityFeePerGas"] = priority_fee
        tx["maxFeePerGas"] = int(base_fee) * 2 + priority_fee
        tx["type"] = "0x2"
        tx.pop("gasPrice", None)
    except Exception as exc:
        _raise_upstream("Failed to configure transaction fee fields from RPC", exc)
    try:
        signed = account.sign_transaction(tx)
        raw_tx = getattr(signed, "raw_transaction", None) or getattr(
            signed, "rawTransaction", None
        )
        if raw_tx is None:
            raise RuntimeError("Signed transaction payload is missing")
        tx_hash = w3.eth.send_raw_transaction(raw_tx)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
    except Exception as exc:
        logger.exception(
            "Failed to submit tx. from=%s to=%s nonce=%s chainId=%s value=%s",
            account.address,
            tx.get("to"),
            tx.get("nonce"),
            tx.get("chainId"),
            value,
        )
        raise HTTPException(
            status_code=502,
            detail=f"Failed to submit transaction to RPC: {str(exc)}",
        ) from exc
    if receipt.status != 1:
        logger.error("Contract transaction reverted. tx_hash=%s", tx_hash.hex())
        raise HTTPException(status_code=502, detail="Transaction failed")
    return tx_hash.hex()


def _call_contract_read(callable_obj, operation: str):
    try:
        return callable_obj.call()
    except HTTPException:
        raise
    except Exception as exc:
        _raise_upstream(f"Contract read failed: {operation}", exc)


def max_price(settings: Settings) -> int:
    """Get the maximum price allowed for listings.

    Args:
        settings (Settings): Application settings instance

    Returns:
        int: Maximum price allowed for listings
    """

    return _call_contract_read(
        _get_contract(settings).functions.MAX_PRICE(),
        "MAX_PRICE",
    )


def fee_bps(settings: Settings) -> int:
    """Get the fee basis points configured in the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        int: Fee basis points configured in the contract
    """

    return _call_contract_read(
        _get_contract(settings).functions.feeBps(),
        "feeBps",
    )


def fee_recipient(settings: Settings) -> str:
    """Get the fee recipient address configured in the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Fee recipient address configured in the contract
    """

    return _call_contract_read(
        _get_contract(settings).functions.feeRecipient(),
        "feeRecipient",
    )


def owner(settings: Settings) -> str:
    """Get the owner address of the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Owner address of the contract
    """

    return _call_contract_read(
        _get_contract(settings).functions.owner(),
        "owner",
    )


def get_item_view(listing_id: str, settings: Settings) -> MarketplaceDataItem:
    """Get the item view for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        settings (Settings): Application settings instance

    Returns:
        MarketplaceDataItem: Item view data
    """

    item_id = uuid_to_bytes32(listing_id)
    raw = _call_contract_read(
        _get_contract(settings).functions.getItemView(item_id),
        "getItemView",
    )
    return _item_view_to_schema(raw)


def get_items(start: int, count: int, settings: Settings) -> List[MarketplaceDataItem]:
    """Get a list of item views from the contract.

    Args:
        start (int): Starting index
        count (int): Number of items to retrieve
        settings (Settings): Application settings instance

    Returns:
        List[MarketplaceDataItem]: List of item views
    """
    raw_items = _call_contract_read(
        _get_contract(settings).functions.getItems(start, count),
        "getItems",
    )
    return [_item_view_to_schema(item) for item in raw_items]


def get_all_items(settings: Settings) -> List[MarketplaceDataItem]:
    """Get all item views from the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        List[MarketplaceDataItem]: List of all item views
    """

    raw_items = _call_contract_read(
        _get_contract(settings).functions.getAllItems(),
        "getAllItems",
    )
    return [_item_view_to_schema(item) for item in raw_items]


def has_access(id: str, wallet_id_bytes: bytes, settings: Settings) -> bool:
    """Check if a wallet has access to a specific listing.

    Args:
        id (str): Listing UUID string
        wallet_id_bytes (bytes): Wallet ID bytes
        settings (Settings): Application settings instance

    Returns:
        bool: True if the wallet has access, False otherwise
    """

    item_id = uuid_to_bytes32(id)
    return _call_contract_read(
        _get_contract(settings).functions.hasAccess(item_id, wallet_id_bytes),
        "hasAccess",
    )


def create_item(
    listing_id: str,
    title: str,
    description: str,
    seller: str,
    price: int,
    dataset_url: str,
    dataset_hash: str,
    signature_url: str,
    signature_hash: str,
    settings: Settings,
) -> str:
    """Create a new item listing in the contract.

    Args:
        listing_id (str): Listing UUID string
        title (str): Item title
        description (str): Item description
        seller (str): Seller address
        price (int): Item price
        dataset_url (str): Dataset URL
        dataset_hash (str): Dataset hash
        signature_url (str): Signature URL
        signature_hash (str): Signature hash
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    try:
        seller_address = Web3.to_checksum_address(seller)
    except ValueError as exc:
        _raise_bad_request("Invalid seller EVM address", exc)
    try:
        dataset_hash_bytes = Web3.to_bytes(hexstr=dataset_hash)
        signature_hash_bytes = Web3.to_bytes(hexstr=signature_hash)
    except Exception as exc:
        _raise_bad_request("Invalid dataset/signature hash format", exc)
    tx = contract.functions.createItem(
        item_id,
        title,
        description,
        seller_address,
        price,
        dataset_url,
        dataset_hash_bytes,
        signature_url,
        signature_hash_bytes,
    )
    return _send_tx(tx, settings)


def buy_item(listing_id: str, value_wei: int, settings: Settings) -> str:
    """Buy an item from the contract.

    Args:
        listing_id (str): Listing UUID string
        value_wei (int): Value in Wei to send with the transaction
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)

    # Pre-check payment so we can return a clean 400 instead of a low-level revert.
    item = _call_contract_read(contract.functions.getItemView(item_id), "getItemView")
    price_wei = int(item[4])
    fee_bps_value = int(_call_contract_read(contract.functions.feeBps(), "feeBps"))
    fee_wei = (price_wei * fee_bps_value) // 10_000
    required_wei = price_wei + fee_wei
    if value_wei < required_wei:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Insufficient payment. required={required_wei} provided={value_wei} "
                f"(price={price_wei}, fee_bps={fee_bps_value})"
            ),
        )

    tx = contract.functions.buyItem(item_id)
    return _send_tx(tx, settings, value=value_wei)


def update_dataset_url(listing_id: str, new_url: str, settings: Settings) -> str:
    """Update the dataset URL for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_url (str): New dataset URL
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.updateDatasetUrl(item_id, new_url)
    return _send_tx(tx, settings)


def update_signature(
    listing_id: str, new_url: str, new_hash: str, settings: Settings
) -> str:
    """Update the signature URL and hash for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_url (str): New signature URL
        new_hash (str): New signature hash
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    try:
        new_hash_bytes = Web3.to_bytes(hexstr=new_hash)
    except Exception as exc:
        _raise_bad_request("Invalid signature hash format", exc)
    tx = contract.functions.updateSignature(item_id, new_url, new_hash_bytes)
    return _send_tx(tx, settings)


def update_price(listing_id: str, new_price: int, settings: Settings) -> str:
    """Update the price for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        new_price (int): New price for the item
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.updatePrice(item_id, new_price)
    return _send_tx(tx, settings)


def set_fee_config(
    fee_recipient_addr: str, fee_bps_value: int, settings: Settings
) -> str:
    """Set the fee recipient address and fee basis points in the contract.

    Args:
        fee_recipient_addr (str): Fee recipient address
        fee_bps_value (int): Fee basis points value
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    try:
        recipient = Web3.to_checksum_address(fee_recipient_addr)
    except ValueError as exc:
        _raise_bad_request("Invalid fee recipient EVM address", exc)
    tx = contract.functions.setFeeConfig(recipient, fee_bps_value)
    return _send_tx(tx, settings)


def transfer_ownership(new_owner: str, settings: Settings) -> str:
    """Transfer ownership of the contract to a new owner.

    Args:
        new_owner (str): New owner's address
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    try:
        owner_address = Web3.to_checksum_address(new_owner)
    except ValueError as exc:
        _raise_bad_request("Invalid new owner EVM address", exc)
    tx = contract.functions.transferOwnership(owner_address)
    return _send_tx(tx, settings)


def renounce_ownership(settings: Settings) -> str:
    """Renounce ownership of the contract.

    Args:
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    tx = contract.functions.renounceOwnership()
    return _send_tx(tx, settings)


def grant_access(listing_id: str, wallet_id_bytes: bytes, settings: Settings) -> str:
    """Grant access to a wallet for a specific listing.

    Args:
        listing_id (str): Listing UUID string
        wallet_id_bytes (bytes): Wallet ID in bytes
        settings (Settings): Application settings instance

    Returns:
        str: Transaction hash
    """

    contract = _get_contract(settings)
    item_id = uuid_to_bytes32(listing_id)
    tx = contract.functions.grantAccess(item_id, wallet_id_bytes)
    return _send_tx(tx, settings)
