export const marketplaceAbi = [
  "function createItem(bytes32 itemId,string title,string description,address seller,uint256 priceAtomic,string datasetUrl,bytes32 datasetHash,string signatureUrl,bytes32 signatureHash)",
  "function buyItem(bytes32 itemId)",
  "function feeBps() view returns (uint256)",
  "function settlementToken() view returns (address)",
  "function getItemView(bytes32 itemId) view returns (tuple(bytes32 itemId,string title,string description,address seller,uint256 priceAtomic,string datasetUrl,bytes32 datasetHash,string signatureUrl,bytes32 signatureHash,bool exists,uint256 purchaseCount))",
  "error Marketplace__InitialOwnerRequired()",
  "error Marketplace__ItemDoesNotExist(bytes32)",
  "error Marketplace__ItemAlreadyExists(bytes32)",
  "error Marketplace__PriceMustBeGreaterThanZero()",
  "error Marketplace__PriceExceedsMaximum(uint256,uint256)",
  "error Marketplace__TitleRequired()",
  "error Marketplace__DescriptionRequired()",
  "error Marketplace__DatasetUrlRequired()",
  "error Marketplace__SignatureUrlRequired()",
  "error Marketplace__InvalidPayment(uint256,uint256)",
  "error Marketplace__AlreadyHasAccess(bytes32,bytes32)",
  "error Marketplace__TransferFailed()",
  "error Marketplace__InvalidFeeBps(uint256)",
  "error Marketplace__FeeRecipientRequired()",
  "error Marketplace__SellerRequired()",
  "error Marketplace__ItemFrozen(bytes32)",
];
